name: Actions

on:
  push:
    paths:
      - ".github/workflows/**"
      - "DungeonCat/**"
  pull_request:
    paths:
      - "**/*"

concurrency:
  group: james_license

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cache
      - uses: actions/cache@v3
        with:
          path: DungeonCat/Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # Test
      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          projectPath: DungeonCat

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: WebGL
          projectPath: DungeonCat
          allowDirtyBuild: true

      # Output
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Build
          path: build

  deploy:
    name: Deploy Site
    needs: build
    runs-on: ubuntu-latest
    permissions: write-all
    # if: github.ref == 'refs/heads/master'
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: Build
          path: Website/public

      - name: Published Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: Website/public
